### ISSUE TITLE
ActiveRecord::UnknownAttributeError: unknown attribute: tag

### ISSUE THREAD

**Issue by mxey** [harley/auditable#4] opened 2012-03-24 17:22 UTC
On every call to update_attributes or save I get this error:

```
ActiveRecord::UnknownAttributeError: unknown attribute: tag
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/attribute_assignment.rb:88:in `block in assign_attributes'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/attribute_assignment.rb:78:in `each'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/attribute_assignment.rb:78:in `assign_attributes'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/persistence.rb:212:in `block in update_attributes'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:190:in `transaction'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/persistence.rb:211:in `update_attributes'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/auditable-0.0.7/lib/auditable/auditing.rb:76:in `snap!'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/auditable-0.0.7/lib/auditable/auditing.rb:28:in `block in audit'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/callbacks.rb:417:in `_run__1211014192793650367__update__3410375624293728312__callbacks'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/callbacks.rb:385:in `_run_update_callbacks'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activesupport-3.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/callbacks.rb:272:in `update'
... 8 levels...
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/validations.rb:50:in `save'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/attribute_methods/dirty.rb:22:in `save'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:241:in `block (2 levels) in save'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:295:in `block in with_transaction_returning_status'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:190:in `transaction'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:208:in `transaction'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:293:in `with_transaction_returning_status'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:241:in `block in save'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:252:in `rollback_active_record_state!'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.0/lib/active_record/transactions.rb:240:in `save'
    from (irb):8
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.0/lib/rails/commands/console.rb:47:in `start'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.0/lib/rails/commands/console.rb:8:in `start'
    from /Users/mxey/.rvm/gems/ruby-1.9.3-p125/gems/railties-3.2.0/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by harley** [comment] 2012-03-24 17:53
thanks for filing the issue. i believe this was caused by not having run the generator. now that the generator bug has been fixed above, i'm closing this, but please reopen if you stil encounter any error after running `rails g auditable:migration` and `rake db:migrate`

**Closed as completed by harley** 2012-03-24 17:53 UTC
